# chatbot usinng cosine similarity

In [2]:
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import TfidfVectorizer

## Starting the chatbot

In [81]:
welcome_words_input = ('hey', 'hello', 'hi')
welcome_words_ouput = ('hey', 'hello', 'hi', 'how are you?', 'welcome', 'how are you doing?')

In [82]:
import random
def welcome_message(text):
    for word in text.split():
        if word.lower() in welcome_words_input:
            return random.choice(welcome_words_ouput)

[0]: 'This is the first document.'
[4]: 'Is this the first document?'
- here we have a question and an answer to it then the similarity is 100%

In [28]:
import spacy
import en_core_web_sm
nlp = spacy.load('en_core_web_sm')
import nltk
from goose3 import Goose
g = Goose()
url = 'https://en.wikipedia.org/wiki/Artificial_intelligence'
article = g.extract(url)

In [24]:
def preprocessing(sentence):
    # a A
    sentence = sentence.lower()
    sentence = sentence.replace('.', '')
    sentence = sentence.replace('[', '')
    tokens = []
    tokens = [token.text for token in nlp(sentence) if not (token.is_stop or token.like_num or token.is_punct or token.is_space or len(token) == 1)]
    tokens = ' '.join([element for element in tokens])

    return tokens

In [25]:
original_sentences = [sentence for sentence in nltk.sent_tokenize(article.cleaned_text)]

In [93]:
def answer(user_text, threshold = 0.2):
    cleaned_sentences = []
    user_text = preprocessing(user_text)
    for sentence in original_sentences:
        pre_sentence=preprocessing(sentence)
        if(user_text != pre_sentence and (len(pre_sentence)-len(user_text))>6):
            cleaned_sentences.append(pre_sentence)
    #print(cleaned_sentences)

    chatbot_answer = ''
    #print(user_text)
    cleaned_sentences.append(user_text)
    #print(cleaned_sentences[-1])

    tfidf = TfidfVectorizer()
    X_sentences = tfidf.fit_transform(cleaned_sentences)
#     print(type(X_sentences))
    #print(X_sentences.toarray()[-1])
    similarity = cosine_similarity(X_sentences[-1], X_sentences)
#     print(similarity)
    sentence_index = similarity.argsort()[0][-2] #to prevent getting the appended same sentence
#     print(sentence_index)
#     print(similarity[0][sentence_index])

    if similarity[0][sentence_index] < threshold:
        chatbot_answer += 'Sorry, no answer was found!'
    else:
        chatbot_answer += original_sentences[sentence_index]

    return chatbot_answer  

In [92]:
answer("ai")

<class 'scipy.sparse.csr.csr_matrix'>


'[u][48]\n\nThe issue is not resolved: sub-symbolic reasoning can make many of the same inscrutable mistakes that human intuition does, such as algorithmic bias.'

In [47]:
type(preprocessing(original_sentences[-2]))

str

In [75]:
original_sentences

['Artificial intelligence (AI) is intelligence demonstrated by machines, as opposed to the natural intelligence displayed by animals including humans.',
 'AI research has been defined as the field of study of intelligent agents, which refers to any system that perceives its environment and takes actions that maximize its chance of achieving its goals.',
 '[a]\n\nThe term "artificial intelligence" had previously been used to describe machines that mimic and display "human" cognitive skills that are associated with the human mind, such as "learning" and "problem-solving".',
 'This definition has since been rejected by major AI researchers who now describe AI in terms of rationality and acting rationally, which does not limit how intelligence can be articulated.',
 '[b]\n\nAI applications include advanced web search engines (e.g., Google), recommendation systems (used by YouTube, Amazon and Netflix), understanding human speech (such as Siri and Alexa), self-driving cars (e.g., Tesla), aut

In [60]:
len('"Logic and Artificial Intelligence."')-len("Artificial intelligence")

13

In [65]:
preprocessing('"Logic and Artificial Intelligence."')

'logic artificial intelligence'

- the finale chat bot about AI

In [94]:
cont = True
print('Hello! I am a chatbot and I will answer your questions about artificial Intelligence')
while cont == True:
    user_text = input()
    if user_text != 'quit':
        if welcome_message(user_text) != None:
            print('Chatbot: ' + welcome_message(user_text))
        else:
            print('Chatbot:')
            print(answer(user_text))  
    else:
        cont = False
        print('Chatbot: Bye! I will see you soon')

Hello! I am a chatbot and I will answer your questions about artificial Intelligence
hi
Chatbot: hi
what is artificial Intelligence
Chatbot:
Artificial intelligence (AI) is intelligence demonstrated by machines, as opposed to the natural intelligence displayed by animals including humans.
what is AI
Chatbot:
[u][48]

The issue is not resolved: sub-symbolic reasoning can make many of the same inscrutable mistakes that human intuition does, such as algorithmic bias.
quit
Chatbot: Bye! I will see you soon


## draft part for test and try methods

In [12]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()
sentences = ['This is the first document.',
             'This document is the second document.',
             'And this is the third document.',
             'Is this the first document?']
sentences.append("where is the first one?")
X = vectorizer.fit_transform(sentences)

In [13]:
print(vectorizer.get_feature_names())

['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this', 'where']


In [14]:
vectorizer.idf_  # result 1 means that the terme is in all sentences

array([2.09861229, 1.18232156, 1.40546511, 1.        , 2.09861229,
       2.09861229, 1.        , 2.09861229, 1.18232156, 2.09861229])

In [15]:
print(X.toarray()[1])

[0.         0.64612571 0.         0.2732445  0.         0.57343426
 0.2732445  0.         0.32306286 0.        ]


In [16]:
X.shape

(5, 10)

In [17]:
type(X)

scipy.sparse.csr.csr_matrix

In [3]:
import numpy as np
X_test_similarity = X[0:2]
X_test_similarity = X_test_similarity.toarray()
X_test_similarity = np.concatenate((X_test_similarity, X_test_similarity[0].reshape(1,-1)), axis = 0)
X_test_similarity # containe the first and the second phrase and a copy of the first one

array([[0.        , 0.45436615, 0.54012022, 0.38429998, 0.        ,
        0.        , 0.38429998, 0.        , 0.45436615, 0.        ],
       [0.        , 0.64612571, 0.        , 0.2732445 , 0.        ,
        0.57343426, 0.2732445 , 0.        , 0.32306286, 0.        ],
       [0.        , 0.45436615, 0.54012022, 0.38429998, 0.        ,
        0.        , 0.38429998, 0.        , 0.45436615, 0.        ]])

In [4]:
cosine_similarity(X_test_similarity[0].reshape(1, -1),X[3].reshape(1,-1))

array([[1.]])

* the simelarity is 1 when the two operand are the same

In [20]:
# my test
# To find the most related documents, we can use cosine_similarites.argsort() 
# to get the most related document similarities values.

similarity = cosine_similarity(X[-1],X[:-2])
# similarity is a 2d array,we take the first and unique array,argsort sort ascendently,return indexes.
sim_index = similarity.argsort()[0][-1]
print(similarity)
print(sim_index)
print(f"Question : {sentences[-1]}")
print(f"The bot : {sentences[sim_index]}")

[[0.42728324 0.15284579 0.15165855]]
0
Question : where is the first one?
The bot : This is the first document.


In [35]:
type(similarity.argsort()[0][0])

numpy.int64

In [36]:
similarity.argsort()

array([[2, 1, 0]], dtype=int64)